name: GitHub actions version updater

on:
  # can be used to run workflow manually
  workflow_dispatch:
  schedule:
  # Automatically run on every 1st of every three months
    - cron:  '0 7 1 */3 *'

jobs:
    check-versions:
    # saadmk11/github doesn't work on Self hosted runner yet 
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4.1.7
              with:
                # Classic personal access token with repo and workflow scope
                token: ${{ secrets.REPO_WORKFLOW_ACCESS_TOKEN }} 

            - name: GitHub Actions Version Updater
              uses: saadmk11/github-actions-version-updater@v0.8.1
              with:
                token: ${{ secrets.REPO_WORKFLOW_ACCESS_TOKEN }}
                pull_request_title: '👷 Monthly actions version update'
                pull_request_team_reviewers: "DevOps"
                pull_request_branch: 'fix/workflow-actions-update'
                pull_request_labels: 'Type: DevOps'
                update_version_with: "release-tag"
                release_types: 'major, minor, patch'